// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0R2sY9xSDhXHQ3ZxGirF15ThzAuheIE',
    appId: '1:1033028471446:web:18eb2c2745204676ead0b7',
    messagingSenderId: '1033028471446',
    projectId: 'autism-app-keerthana',
    authDomain: 'autism-app-keerthana.firebaseapp.com',
    storageBucket: 'autism-app-keerthana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzNMJ1CjGpF1211YfgdqJ1pQg7UVYmn_c',
    appId: '1:1033028471446:android:463bec2b1db84a57ead0b7',
    messagingSenderId: '1033028471446',
    projectId: 'autism-app-keerthana',
    storageBucket: 'autism-app-keerthana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndXt9kWc-3ZrW7_1EvI9vL9UxCZSPxzA',
    appId: '1:1033028471446:ios:b5af5b67e2a5cd0bead0b7',
    messagingSenderId: '1033028471446',
    projectId: 'autism-app-keerthana',
    storageBucket: 'autism-app-keerthana.firebasestorage.app',
    iosBundleId: 'com.example.autismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndXt9kWc-3ZrW7_1EvI9vL9UxCZSPxzA',
    appId: '1:1033028471446:ios:b5af5b67e2a5cd0bead0b7',
    messagingSenderId: '1033028471446',
    projectId: 'autism-app-keerthana',
    storageBucket: 'autism-app-keerthana.firebasestorage.app',
    iosBundleId: 'com.example.autismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw0R2sY9xSDhXHQ3ZxGirF15ThzAuheIE',
    appId: '1:1033028471446:web:56dfed0d2d907475ead0b7',
    messagingSenderId: '1033028471446',
    projectId: 'autism-app-keerthana',
    authDomain: 'autism-app-keerthana.firebaseapp.com',
    storageBucket: 'autism-app-keerthana.firebasestorage.app',
  );
}
